function submitForm(f) {
  if (confirm('Вы уверены, что хотите отправить форму?')) f.submit()
}
function MyFunction1() {
  let c = document.getElementById('par')
  c.innerHTML =
    'LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. A NESCIUNT ET EX DEBITIS QUASI, ADIPISCI OFFICIIS SUSCIPIT NISI PARIATUR IPSA DICTA DOLOREMQUE ALIAS. OPTIO DELECTUS ITAQUE QUIDEM, REPUDIANDAE QUASI POSSIMUS OFFICIA! ERROR REPUDIANDAE BLANDITIIS FACILIS DUCIMUS MOLESTIAE TEMPORA QUO DOLOR ACCUSAMUS EXPLICABO VITAE! TEMPORIBUS, LIBERO QUOD EAQUE DELECTUS OFFICIIS, TEMPORA MOLLITIA NOBIS ASSUMENDA ERROR, TOTAM RATIONE AMET ARCHITECTO!'
}

function MyFunction2() {
  let c = document.getElementById('par')
  c.innerHTML =
    'LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. A NESCIUNT ET EX DEBITIS QUASI, ADIPISCI OFFICIIS SUSCIPIT NISI PARIATUR IPSA DICTA DOLOREMQUE ALIAS. OPTIO DELECTUS ITAQUE QUIDEM, REPUDIANDAE QUASI POSSIMUS OFFICIA!'
}
function MyFunction3() {
  let c = document.getElementById('par')
  c.innerHTML =
    'LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. A NESCIUNT ET EX DEBITIS QUASI, ADIPISCI OFFICIIS SUSCIPIT NISI PARIATUR IPSA DICTA DOLOREMQUE ALIAS. OPTIO DELECTUS ITAQUE QUIDEM, REPUDIANDAE QUASI POSSIMUS OFFICIA!LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. A NESCIUNT ET EX DEBITIS QUASI, ADIPISCI OFFICIIS SUSCIPIT NISI PARIATUR IPSA DICTA DOLOREMQUE ALIAS. OPTIO DELECTUS ITAQUE QUIDEM, REPUDIANDAE QUASI POSSIMUS OFFICIA!LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. A NESCIUNT ET EX DEBITIS QUASI, ADIPISCI OFFICIIS SUSCIPIT NISI PARIATUR IPSA DICTA DOLOREMQUE ALIAS. OPTIO DELECTUS ITAQUE QUIDEM, REPUDIANDAE QUASI POSSIMUS OFFICIA!LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. A NESCIUNT ET EX DEBITIS QUASI, ADIPISCI OFFICIIS SUSCIPIT NISI PARIATUR IPSA DICTA DOLOREMQUE ALIAS. OPTIO DELECTUS ITAQUE QUIDEM, REPUDIANDAE QUASI POSSIMUS OFFICIA!'
}
